"""Feature definitions for Feast."""
from datetime import timedelta
from feast import Entity, FeatureView, Field, FileSource
from feast.types import Float32, Int64

# -----------------------------------------------------------------------------
# 1. Entity Definition
# -----------------------------------------------------------------------------
# The primary key that links features to a specific patient.
patient = Entity(
    name="patient_id", 
    join_keys=["patient_id"], 
    description="Unique identifier for the patient"
)

# -----------------------------------------------------------------------------
# 2. Offline Data Sources (Parquet files generated by ingestion.py)
# -----------------------------------------------------------------------------
# Source A: The 630k Synthetic Records (Pre-training)
synthetic_source = FileSource(
    name="synthetic_history",
    path="../data/processed/synthetic_features.parquet",
    timestamp_field="event_timestamp",
    created_timestamp_column="created_timestamp",
)

# Source B: The 270 Real Clinical Records (Fine-Tuning / Streaming)
clinical_source = FileSource(
    name="clinical_stream",
    path="../data/processed/clinical_features.parquet",
    timestamp_field="event_timestamp",
    created_timestamp_column="created_timestamp",
)

# -----------------------------------------------------------------------------
# 3. Feature Schema 
# (Mapping to standard UCI Heart Disease features)
# -----------------------------------------------------------------------------
clinical_features_schema = [
    Field(name="age", dtype=Float32),
    Field(name="sex", dtype=Int64),           # 1=Male, 0=Female
    Field(name="cp", dtype=Int64),            # Chest pain type (0-3)
    Field(name="trestbps", dtype=Float32),    # Resting blood pressure
    Field(name="chol", dtype=Float32),        # Serum cholesterol in mg/dl
    Field(name="fbs", dtype=Int64),           # Fasting blood sugar > 120 mg/dl
    Field(name="restecg", dtype=Int64),       # Resting ECG results (0-2)
    Field(name="thalach", dtype=Float32),     # Maximum heart rate achieved
    Field(name="exang", dtype=Int64),         # Exercise induced angina (1=yes)
    Field(name="oldpeak", dtype=Float32),     # ST depression induced by exercise
    Field(name="slope", dtype=Int64),         # Slope of peak exercise ST segment
    Field(name="ca", dtype=Int64),            # Number of major vessels (0-3)
    Field(name="thal", dtype=Int64),          # 1=normal, 2=fixed defect, 3=reversable
]

# -----------------------------------------------------------------------------
# 4. Feature Views (Isolating the distributions)
# -----------------------------------------------------------------------------
# View A: For Phase 1 Pre-training
synthetic_patient_fv = FeatureView(
    name="synthetic_patient_features",
    entities=[patient],
    ttl=timedelta(days=3650), # 10 year TTL to allow historical retrieval
    schema=clinical_features_schema,
    source=synthetic_source,
)

# View B: For Phase 2 Fine-Tuning and FastAPI Online Inference
clinical_patient_fv = FeatureView(
    name="clinical_patient_features",
    entities=[patient],
    ttl=timedelta(days=3650),
    schema=clinical_features_schema,
    source=clinical_source,
)